package com.curtisnewbie.module.auth.dao;

import java.util.Date;

/**
 * Database Table Remarks:
 *   access log
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table access_log
 */
public class AccessLogEntity {

    /** primary key */
    private Integer id;

    /** when the user signed in */
    private Date accessTime;

    /** ip address */
    private String ipAddress;

    /** username */
    private String username;

    /** primary key of user */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.id
     *
     * @return the value of access_log.id
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.id
     *
     * @param id the value for access_log.id
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.access_time
     *
     * @return the value of access_log.access_time
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.access_time
     *
     * @param accessTime the value for access_log.access_time
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.ip_address
     *
     * @return the value of access_log.ip_address
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.ip_address
     *
     * @param ipAddress the value for access_log.ip_address
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.username
     *
     * @return the value of access_log.username
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.username
     *
     * @param username the value for access_log.username
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.user_id
     *
     * @return the value of access_log.user_id
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.user_id
     *
     * @param userId the value for access_log.user_id
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "AccessLogEntity{" +
                "id=" + id +
                ", accessTime=" + accessTime +
                ", ipAddress='" + ipAddress + '\'' +
                ", username='" + username + '\'' +
                ", userId=" + userId +
                '}';
    }
}